### ISSUE TITLE
Toolbar Position is Incorrect with `direction: rtl`

### ISSUE THREAD

**Issue by MhL5** [aidenybai/react-scan#190]
![image](https://github.com/user-attachments/assets/d3cff818-9b23-4af2-a920-9479a1e53e90)

When using the React Scan library with `direction: rtl`, the toolbar position is incorrect. If I drag the toolbar, it even goes outside of the page, and I have to clear localStorage to reset the position.

 i have tried changing the direction of the toolbar to `ltr` but it didn't solve the problem
 ```css
  #react-scan-toolbar,
  #react-scan-toolbar * {
    direction: ltr !important;
  }
 ```

## Steps to Reproduce
```css
* {
    direction: rtl;
  }
  ```
  ```html
  <html dir="rtl"> ... </html>
  ```
