### ISSUE TITLE
Why is the scrollbar being reset globally?

### ISSUE THREAD

**Issue by mthezi** [aidenybai/react-scan#42]
This library will globally change the appearance of scrollbars!
```css
* {
    scrollbar-width: thin;
    scrollbar-color: rgba(255, 255, 255, 0.3) rgba(255, 255, 255, 0.1);
}
```

I spent an hour troubleshooting the scrollbar issue on my page!
